### ISSUE TITLE
no declaration for var 'endorsementHash2'  /test/functional/SmartIdentity.js

### ISSUE THREAD

**Issue by emptybytes** [SmartIdentity/smartId-contracts#10]

**Comment by dci-aloughran** [comment]
## What is wrong?

There is no declaration for the variable 'endoresementHash2' in /test/functional/SmartIdentity/endorsementtest.js

## How could it be / was it fixed?

Make sure that the variable is declared before it's used.

**Comment by dci-aloughran** [comment]
Fixed by #12
