### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by xaviershay** [SmartIdentity/smartId-contracts#11]
Hello! This project is interesting, but I don't see commits in the last 6 months.

* Is the project continuing in private? Hit intractable technical problems? Run out of budget? Run out of motivation? Finished?
* How does it compare to projects like [Blockchain Helix](http://blockchain-helix.com/) and [KYC-Chain](http://kyc-chain.com/#why)?

Thanks!

**Comment by dci-aloughran** [comment]
Hi Xavier,

I'll give you a more comprehensive answer next week.

The reason for opening it up to the community is to try and get more people involved in the development and maintenance.  The contract as it stands has been good enough for our current use cases, but we're acutely aware that to stay on top of solidity development for a live implementation we'd have to be refreshing and re-testing the contracts more often.

There are now 60 stars on the repo and 26 forks; so hopefully we can begin to foster some feedback and contributions to keep developing the contracts on this repository.

Kind Regards,

Andy Loughran

**Comment by dci-aloughran** [comment]
There is much in the pipeline, mostly additional off chain components which will support the on chain smart contract code to lower the bar for developers looking to utilise the protocol. We do anticipate further changes to the solidity contract in future to enable additional functional and security features, but for now it supports the core scenarios we are focused on.

**Comment by xaviershay** [comment]
Thanks!
